from enum import StrEnum


class PendingStatus(StrEnum):
    TODAS = "TODAS"
    SENHA_PENDENTE = "SENHA PENDENTE"
    EXECUCAO_PENDENTE = "EXECUÇÃO PENDENTE"
    ANALISE_OPERADORA = "ANALISE OPERADORA"
    SENHA_PENDENTE_ATIVACAO = "SENHA PENDENTE ATIVAÇÃO"
    PROCEDIMENTO_INDEFERIDO = "PROCEDIMENTO INDEFERIDO"
